<<<<<<< HEAD
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

after_success:
  - snyk monitor

cache:
  directories:
  - $HOME/.m2

  
# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
